name: Deploy
on:
  workflow_dispatch:
  release:
    types: [published]

env:
  DOTNET_VERSION: "8.0.x"
  ARTIFACT_FOLDER: "artifacts"

jobs:
  deploy:
    name: NuGet Packages
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Clean Artifacts Folder
        run: |
          if (Test-Path "${{ env.ARTIFACT_FOLDER }}") {
            Remove-Item -Recurse -Force "${{ env.ARTIFACT_FOLDER }}"
          }
        shell: powershell
        
      - name: Package ScikitLearn.Net
        env:
          PROJECT_FOLDER: "Source/ScikitLearn"
        run: |
          dotnet restore "${{ env.PROJECT_FOLDER }}"
          dotnet build "${{ env.PROJECT_FOLDER }}" --configuration Release --no-restore
          dotnet pack "${{ env.PROJECT_FOLDER }}" --configuration Release --no-build -o "${{ env.ARTIFACT_FOLDER }}"
        
      - name: Deploy Packages to NuGet
        run: |
          dotnet nuget push "${{ env.ARTIFACT_FOLDER }}/*.nupkg" `
            --api-key ${{ secrets.NUGET_API_KEY }} `
            --source https://api.nuget.org/v3/index.json `
            --skip-duplicate
        shell: powershell